name = "VastCraft"
author = "vastlyadequate"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87c25462a7ff8311e55f301a42c272ce4f7eec5363c70e49cc4a5df148eac835"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
