name = "VastCraft"
author = "vastlyadequate"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56715f4aaf78d4aa2a6510e2a8161303550093b1bf16b221f98121a72477bd7b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
